### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by zoberandi** [philip1986/iwy_master#1]
Thank you a lot for sharing your code here!
But i have a Problem which is crashing IWY every time when i use the on_off.js: the bulb flashes in green an then turns off with this Error:

```sh
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
(node) warning: possible EventEmitter memory leak detected. 11 connTimeout listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at IwyMaster.addListener (events.js:179:15)
    at IwyMaster.once (events.js:204:8)
    at IwyMaster._send (/home/zober/node_modules/iwy_master/index.js:109:8)
    at IwyMaster.switchOn (/home/zober/node_modules/iwy_master/index.js:218:8)
    at /home/zober/Downloads/iwy_master-master/examples/on_off.js:29:13
    at /home/zober/node_modules/iwy_master/index.js:139:11
    at afterWrite (_stream_writable.js:361:3)
    at _stream_writable.js:349:9
    at process._tickCallback (node.js:355:11)
[Error: connection timeout]
[Error: connection timeout]
{ [Error: This socket has been ended by the other party] code: 'EPIPE' }
[Error: connection timeout]
```

Can you help me?

**Comment by philip1986** [comment]
The example is actually not the best. For a use-case like this (flash in an given interval) there are bulid-in programms which are executed by the bulb itself, but this is currently not supported by the driver. So you should not use the driver to execute something in an interval. I will change the example asap, thanks for pointing it out.

**Comment by zoberandi** [comment]
Thank you guy!
